#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

scp -i "$SSH_KEY_PATH" -O StrictHostKeyChecking=no "$PATH" "$USERNAME@$SERVER_IP:~/"
