#!/usr/bin/env bash
#This Shebang makes my bash portable in that I do not need to 
#+ use absolute paths.
i=0
while [ $i -lt 10 ];
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
